#!/bin/bash

################################################################################
#                                                                              #
#                                 {o,o}                                        #
#                                 |)__)                                        #
#                                 -"-"-                                        #
#                                                                              #
################################################################################
#
#This script dumps a local mongo database and backs it up.
#
##############################---INCLUDES---####################################

. "${BACKUP_BACKEND}.cf"
. ./runDuplicity

################################################################################

##############################---VARIABLES---###################################

#Mising variables are included from backupConfig
SOURCE_DIRECTORY="${BACKUPDIR}/${BACKUP_NAME}"
DESTINATION="${SOURCE_DIRECTORY}/${DATABASE}"

################################################################################

##############################---FUNCTIONS---###################################

function dump() {
    if  [ -e ${SOURCE_DIRECTORY} ]
    then
        rm -fr ${SOURCE_DIRECTORY}
    fi

    mkdir -p ${SOURCE_DIRECTORY}
    mongodump \
        -h 127.0.0.1 \
        -d ${DATABASE} \
         --quiet \
        --out ${DESTINATION}
}

function runBackup() {
    dump
    runDuplicity
    removeOldBackups
}

################################################################################
