#!/bin/bash

################################################################################
#                                                                              #
#                                 {o,o}                                        #
#                                 |)__)                                        #
#                                 -"-"-                                        #
#                                                                              #
################################################################################
#
# Back up a remote location with duplicity
#
##############################---INCLUDES---####################################

. "${BACKUP_BACKEND}.cf"
. ./runDuplicity

################################################################################

##############################---FUNCTIONS---###################################

function prep_for_backup() {
    export SOURCE_DIRECTORY="${BASE_MOUNT_DIR}/${BACKUP_NAME}"
    mkdir -p "${SOURCE_DIRECTORY}"
    echo " > Mounting remote directory"
    sshfs "${REMOTE_HOST}:/${REMOTE_SOURCE_DIRECTORY}" "${SOURCE_DIRECTORY}"
}

function after_backup_cleanup() {
    echo " > Cleaning up"
    echo " > Unmounting remote directory"
    umount "${SOURCE_DIRECTORY}"
    unset SOURCE_DIRECTORY
}

function runBackup() {
    prep_for_backup
    runDuplicity
    removeOldBackups
    after_backup_cleanup
}

################################################################################
