#!/bin/bash

################################################################################
#                                                                              #
#                                 {o,o}                                        #
#                                 |)__)                                        #
#                                 -"-"-                                        #
#                                                                              #
################################################################################
#
# Back up a location with duplicity
#
##############################---INCLUDES---####################################

. "${BACKUP_BACKEND}.cf"
. ./runDuplicity

################################################################################

##############################---FUNCTIONS---###################################

function runBackup() {
  gitlabBackup
  runDuplicity
  removeOldBackups
}

function gitlabBackup() {
  docker exec "${DOCKER_CONTAINER}" bash -c "gitlab-rake gitlab:backup:create SKIP=repositories" >> /dev/null
}

################################################################################
