#!/bin/bash

################################################################################
#                                                                              #
#                                 {o,o}                                        #
#                                 |)__)                                        #
#                                 -"-"-                                        #
#                                                                              #
################################################################################
#
# Test restore of backups
#
#################################---ENV---######################################

set -e

################################################################################

##############################---VARIABLES---###################################

VERIFY_LOGDIR="/var/log/backup/verify_backup_integrity"
MAIL_TO="{{ duplicity_mail_to }}"
MAIL_FROM="{{ duplicity_mail_from }}"

################################################################################

###############################---WORKDIR---####################################

cd $( dirname $0 )

################################################################################

##############################---FUNCTIONS---###################################

function verifyBackup_full() {
  for backup in *.conf
  do
    verifyBackup "${backup}"
  done
}

function verifyBackup() {
  backup=${1}
  unset DESTINATION_ROOT_DIR
  . "./${backup}"
  . "${BACKUP_BACKEND}.cf"
  export PASSPHRASE="${GPG_PASSPHRASE}"
  verify_logfile="${VERIFY_LOGDIR}/${BACKUP_NAME}"
  PASSPHRASE="${GPG_PASSPHRASE}" duplicity verify  --encrypt-key "${GPG_KEY}" \
                  --gpg-binary "{{ duplicity_gpg_binary }}" \
                   "${DESTINATION_URL}" "${TMPDIR}/${BACKUP_NAME}" | tee -a "${verify_logfile}"
}

function prep_env() {
  rm -fr "${VERIFY_LOGDIR}"
  mkdir -p "${VERIFY_LOGDIR}"
  export TMPDIR=${TMPDIR:-/storage/backup/tmp}
  mkdir -p "${TMPDIR}"
}

################################################################################

###############################---EXECUTION---##################################

prep_env
if [ -z ${1} ]
then
  verifyBackup_full
else
  verifyBackup "${1}"
fi

################################################################################
