#!/bin/bash

################################################################################
#                                                                              #
#                                 {o,o}                                        #
#                                 |)__)                                        #
#                                 -"-"-                                        #
#                                                                              #
################################################################################
#
#Runs duplicity
#
##############################---FUNCTIONS---###################################

function runDuplicity() {
  if [ ! -d ${SOURCE_DIRECTORY} ]
  then
      echo "Backup source directory does not exist"
      exit 1
  fi

  echo "################################################################################" >> "${LOGFILE}"
  echo "# Started the backup of ${BACKUP_NAME} - $(date)" >> "${LOGFILE}"
  echo "" >> "${LOGFILE}"
  echo "################################################################################" >> "${DUPLICITYLOG}"
  echo "# Started the backup of ${BACKUP_NAME}" >> "${DUPLICITYLOG}"
  echo "" >> "${DUPLICITYLOG}"

  if [ "${PROTO}" = "rsync" ]
  then
    mkdir -p "tmp/${BACKUP_NAME}"
    RSYNC_PASSWORD="${PASSWORD}" rsync -a --recursive  "tmp/${BACKUP_NAME}" "${PROTO}://${USERNAME}@${SERVER}:${PORT}/${MODULE}" >> /dev/null
    rmdir "tmp/${BACKUP_NAME}"
  fi
  PASSPHRASE="${GPG_PASSPHRASE}"    duplicity --full-if-older-than "${FULL_BACKUP_INTERVAL}" \
          --num-retries 10 \
          --encrypt-key "${GPG_KEY}" \
          --gpg-binary "/usr/bin/gpg2" \
          --log-file ${DUPLICITYLOG} \
          "${SOURCE_DIRECTORY}" \
          "${DESTINATION_URL}" >> "${LOGFILE}"
}


function removeOldBackups() {
  PASSPHRASE="${GPG_PASSPHRASE}"    duplicity remove-all-but-n-full ${SETS_TO_KEEP} \
          --num-retries 10 \
          --encrypt-key "${GPG_KEY}" \
          --gpg-binary "/usr/bin/gpg2" \
          --force \
          --log-file ${DUPLICITYLOG} \
          ${DESTINATION_URL} >> "${LOGFILE}"
  }

################################################################################
