#!/bin/bash

################################################################################
#                                                                              #
#                                 {o,o}                                        #
#                                 |)__)                                        #
#                                 -"-"-                                        #
#                                                                              #
################################################################################
#
# This script dumps all databases from a mysql docker container to a file.
#
##############################---INCLUDES---####################################

. ./backupConfig
. ./runDuplicity

################################################################################

##############################---VARIABLES---###################################

DBUSER="postgres"
DBHOST="localhost"

#Mising variables are included from backupConfig
SOURCE_DIRECTORY="${BACKUPDIR}/${BACKUP_NAME}"
DESTINATION="${SOURCE_DIRECTORY}/dump.sql"

################################################################################

##############################---FUNCTIONS---###################################

function connectAndDump() {
    if  [ -e ${SOURCE_DIRECTORY} ]
    then
        rm -fr ${SOURCE_DIRECTORY}
    fi

    mkdir -p ${SOURCE_DIRECTORY}
    docker exec "${CONTAINER}" bash -c \
            "mysqldump \
                -u ${MYSQL_USER} \
                -p${MYSQL_PASSWORD} \
                --all-databases" > ${DESTINATION}
}

function runBackup() {
    connectAndDump
    runDuplicity
    removeOldBackups
}

################################################################################
