#!/bin/bash

################################################################################
#                                                                              #
#                                 {o,o}                                        #
#                                 |)__)                                        #
#                                 -"-"-                                        #
#                                                                              #
################################################################################
#
#This script dumps the database from a postgresql docker container
#to the destonation file.
#
##############################---INCLUDES---####################################

. ./backupConfig
. ./runDuplicity

################################################################################

##############################---VARIABLES---###################################

DBUSER="postgres"
DBHOST="localhost"

#Mising variables are included from backupConfig
SOURCE_DIRECTORY="${BACKUPDIR}/${BACKUP_NAME}"
DESTINATION="${SOURCE_DIRECTORY}/${DATABASE}.sql"

################################################################################

##############################---FUNCTIONS---###################################

function connectAndDump() {
    if  [ -e ${SOURCE_DIRECTORY} ]
    then
        rm -fr ${SOURCE_DIRECTORY}
    fi

    mkdir -p ${SOURCE_DIRECTORY}
    docker exec "${CONTAINER}" bash -c \
            "pg_dump \
                -U ${DBUSER} \
                -h ${DBHOST} \
                ${DATABASE}" > ${DESTINATION}
}

function runBackup() {
    connectAndDump
    runDuplicity
    removeOldBackups
}

################################################################################
