#!/bin/bash

################################################################################
#                                                                              #
#                                 {o,o}                                        #
#                                 |)__)                                        #
#                                 -"-"-                                        #
#                                                                              #
################################################################################
#
#Runs duplicity
#
##############################---FUNCTIONS---###################################

function runDuplicity() {
    if [ ! -d ${SOURCE_DIRECTORY} ]
    then
        echo "Backup source directory does not exist"
        exit 1
    fi

    echo "################################################################################" >> "${LOGFILE}"
    echo "# Started the backup of ${BACKUP_NAME}" >> "${LOGFILE}"
    echo "" >> "${LOGFILE}"
    echo "################################################################################" >> "${DUPLICITYLOG}"
    echo "# Started the backup of ${BACKUP_NAME}" >> "${DUPLICITYLOG}"
    echo "" >> "${DUPLICITYLOG}"

    duplicity --full-if-older-than "${FULL_BACKUP_INTERVAL}" \
        --no-encryption \
        --log-file ${DUPLICITYLOG} \
        "${SOURCE_DIRECTORY}" \
        "${DESTINATION_URL}" >> "${LOGFILE}"
}

function removeOldBackups() {
    duplicity remove-all-but-n-full ${SETS_TO_KEEP} \
        --no-encryption \
        --force \
        --log-file ${DUPLICITYLOG} \
        ${DESTINATION_URL} >> "${LOGFILE}"
}

################################################################################
