#!/bin/bash

################################################################################
#                                                                              #
#                                 {o,o}                                        #
#                                 |)__)                                        #
#                                 -"-"-                                        #
#                                                                              #
################################################################################
#
#Runs duplicity
#
##############################---FUNCTIONS---###################################

runDuplicity() {
    if [ ! -d ${DESTINATION_DIRECTORY} ]
    then
        echo "Backup source directory does not exist"
        exit 1
    fi

    echo "> Started the backup of ${BACKUP_NAME}" >> "${LOGFILE}"
    duplicity --full-if-older-than "${FULL_BACKUP_INTERVAL}" \
        --no-encryption \
        --ssh-backend pexpect \
        --log-file ${DUPLICITYLOG} \
        "${DESTINATION_DIRECTORY}" \
        "${SFTPLINK}" >> "${LOGFILE}"
}

removeOldBackups() {
    duplicity remove-all-but-n-full ${SETS_TO_KEEP} \
        --no-encryption \
        --ssh-backend pexpect \
        --force \
        --log-file ${DUPLICITYLOG} \
        ${SFTPLINK} >> "${LOGFILE}"
}

################################################################################
