#!/bin/bash

################################################################################
#                                                                              #
#                                 {o,o}                                        #
#                                 |)__)                                        #
#                                 -"-"-                                        #
#                                                                              #
################################################################################
#
#Server specific information to connect to backup location
#It is presumed that the backup location is properly configured, that is:
#It is configured with the client's public key
#
##############################---VARIABLES---###################################

{% if item.local_backup_dir is defined %}
#Local backup destination directory
LOCAL_BACKUP_DIR="{{ item.local_backup_dir }}"
{% else %}
#Login name for backup server
USERNAME="{{ item.username }}"
{% if item.password is defined %}
#Login name for backup server
PASSWORD="{{ item.password }}"
{% endif %}
{% if item.module is defined %}
#Login name for backup server
MODULE="{{ item.module }}"
{% endif %}
#Backup server name
SERVER="{{ item.address }}"
#Backup server port
PORT="{{ item.port }}"
#Location of backup directory.
{% endif %}
LOGDIR="{{ duplicity_log_directory }}"
#Backup directory - here
BACKUPDIR="{{ backup_directory }}"
#Duplicity log file
DUPLICITYLOG="{{ duplicity_log }}"
# GPG passphrase to unlock gpg key
GPG_PASSPHRASE="{{ duplicity_gpg_passphrase }}"
# GPG key
GPG_KEY="{{ item.gpg_key }}"
#Protocol for connection
PROTO="{{ item.proto }}"

#Derived variables
LOGFILE="${LOGDIR}/${BACKUP_NAME}.log"
{% if item.proto == "local" %}
DESTINATION_URL="FILE://${LOCAL_BACKUP_DIR}/${BACKUP_NAME}"
{% else %}
{% if item.proto == "rsync" %}
DESTINATION_URL="${PROTO}://${USERNAME}:${PASSWORD}@${SERVER}:${PORT}::/${MODULE}/${BACKUP_NAME}"
{% else %}
DESTINATION_URL="${PROTO}://${USERNAME}@${SERVER}:${PORT}/${BACKUP_NAME}"
{% endif %}
{% endif %}

################################################################################

###############################---EXECUTION---##################################

mkdir -p ${LOGDIR}

################################################################################
