#!/bin/bash

################################################################################
#                                                                              #
#                                 {o,o}                                        #
#                                 |)__)                                        #
#                                 -"-"-                                        #
#                                                                              #
################################################################################
#
#Server specific information to connect to backup location
#It is presumed that the backup location is properly configured, that is:
#It is configured with the client's public key
#
##############################---VARIABLES---###################################

{% if duplicity_local_backup_dir is defined %}
#Local backup destination directory
LOCAL_BACKUP_DIR="{{ duplicity_local_backup_dir }}"
{% else %}
#Login name for backup server
USERNAME="{{ duplicity_sftp_username }}"
#Backup server name
SERVER="{{ duplicity_sftp_destination }}"
#Backup server port
PORT="{{ duplicity_sftp_port }}"
#Location of backup directory.
{% endif %}
LOGDIR="{{ duplicity_log_directory }}"
#Backup directory - here
BACKUPDIR="{{ backup_directory }}"
#Duplicity log file
DUPLICITYLOG="{{ duplicity_log }}"

#Derived variables
LOGFILE="${LOGDIR}/${BACKUP_NAME}.log"
{% if duplicity_local_backup_dir is defined %}
DESTINATION_URL="FILE://${LOCAL_BACKUP_DIR}/${BACKUP_NAME}"
{% else %}
DESTINATION_URL="sftp://${USERNAME}@${SERVER}:${PORT}/${BACKUP_NAME}"
{% endif %}

################################################################################

###############################---EXECUTION---##################################

mkdir -p ${LOGDIR}

################################################################################
